### ISSUE TITLE
problem with the script "01_ForestLoss_Summaries.py"

### ISSUE THREAD

**Issue by juandavidgutier** [matthias-baumann/baumiTools#1]
Dear @matthias-baumann 

I am trying to reproduce the results of the script "01_ForestLoss_Summaries.py". I downloaded the forest data from Hansen et al. 2013, and I have three .vrt files. Similarly, I have a shape file of the municipalities of Colombia. 
Unfortunately, I could not install the baumiTools in my computer and I had to include the function "CopyToMem" in the script. The script is not showing errors, but it does not write any value in the file "Sumaries.csv"

[Here](https://github.com/juandavidgutier/reproduce_forest_loss) is my script, the .vrt files, and the shape file.

I will appreciate a lot your cooperation.

Regards,

Juan David

**Comment by matthias-baumann** [comment]
Hello Juan,

 

Thanks for the message. The baumiTools are not an official package but you need to download the entire folder and copy it into your site-packages folder in your py-environment. Alternatively, you just take the function “CopyToMem” from the respective scripts in the repository and copy it into your script. Then python should recognize the function.

 

Hope that helps
Matthias

 

From: juandavidgutier ***@***.***> 
Sent: Monday, September 12, 2022 20:59
To: matthias-baumann/baumiTools ***@***.***>
Cc: Matthias ***@***.***>; Mention ***@***.***>
Subject: [matthias-baumann/baumiTools] problem with the script "01_ForestLoss_Summaries.py" (Issue #1)

 

Dear @matthias-baumann <https://github.com/matthias-baumann> 

I am trying to reproduce the results of the script "01_ForestLoss_Summaries.py". I downloaded the forest data from Hansen et al. 2013, and I have three .vrt files. Similarly, I have a shape file of the municipalities of Colombia.
Unfortunately, I could not install the baumiTools in my computer and I had to include the function "CopyToMem" in the script. The script is not showing errors, but it does not write any value in the file "Sumaries.csv"

Here <https://github.com/juandavidgutier/reproduce_forest_loss>  is my script, the .vrt files, and the shape file.

I will appreciate a lot your cooperation.

Regards,

Juan David

**Comment by juandavidgutier** [comment]
Hi @matthias-baumann 

Thanks a lot for your cooperation.

Best regards,

Juan David
